'use client'

import { ReactNode } from "react";
import { QueryClient, QueryClientProvider } from "react-query";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  weight: ['300', '400', '700'],
  style: ['normal'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface ChildrenProps {
  children: ReactNode
}

export default function RootLayout({ children }: ChildrenProps) {

  return (
    <html lang="pt-BR" className="scroll-smooth">
      <body className={`${poppins.className} bg-zinc-900 text-zinc-50`}>
        <QueryClientProvider client={new QueryClient({
          defaultOptions: {
            queries: {
              refetchOnWindowFocus: false,
              retry: 2
            }
          }
        })}
        >
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
